### ISSUE TITLE
Create boot-only cycle to monitor startup latency e2e

### ISSUE THREAD

**Issue by thedeeno** [livepeer/livepeer-test-infra#18]
Right now we have volatile visibility into the platform's startup latency. This seems like a good case for the test streamers to experience (and measure) startup latency in the same way an end user would.

Definition of Done:
- [ ] a boot only streamer is created and deployed
- [ ] downloads one source segment and records latency from broadcast start
- [ ] downloads one transcoded segment and records latency from broadcast start
- [ ] logs the above to papertrail

**Comment by iameli** [comment]
Reprioritizing this for now.
