### ISSUE TITLE
add option for test streams to load directly from Datapacket (instead of from the CDN)

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-test-infra#20]
The continuous monitoring eats up quite a bit of bandwidth, which roughly translates to a few hundred dollars per month of bandwidth bills.  Since we have a lot of test streams now, and the CDN isn't doing ANYTHING in the case of a single viewer, let's move to loading the HLS output directly from the Datapacket servers.

@thedeeno please work with @iameli to get the correct HLS endpoint.

**Comment by thedeeno** [comment]
@ericxtang I'll update the streamers to do this.

My only concern is that we've seen actually seen a stackpath related outage in the past month.

What about using much lower resolution continuous test streams for the long-cycles? This might allow us to keep exercising the CDN for half the test-sessions but also reduce the bandwidth costs enough. Thoughts?

**Comment by thedeeno** [comment]
We can also reduce the number of profiles configured in the stream.

**Comment by ericxtang** [comment]
@thedeeno since we don't have a way to address stackpath outage for now, I think it's ok to accept it as is, and rely on their status page to tell us about downtime (we already subscribe to it).

Reducing the number of profiles is a solution here, but since the biggest bandwidth consumption comes from the source resolution (which we cannot remove), it would limit our ability to accomplish the goal of reducing CDN bandwidth usage in our monitoring streams.

**Comment by wohlner** [comment]
Per convo with @iameli, this is done.
